### ISSUE TITLE
Elegoo Mars 4 Ultra upload

### ISSUE THREAD

**Issue by Stacked99** [vvuk/cassini#2]
File successfully transfered, but threw an exception:

PS P:\Documents\3d Printing\To Print> python C:\working\cassini-main\cassini.py upload 93762_147278_699119_char_mm.goo
13:47:57,454 INFO: Printer: Mars 4 Ultra (ELEGOO Mars 4 Ultra) (Redacted)
93762_147278_699119_char_mm.goo |████████████████████████████████████████| 100% [119561469/119561469] (4470118.45/s)
Exception ignored in: <function StreamWriter.__del__ at 0x00000196B27B5080>
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\streams.py", line 396, in __del__
    self.close()
  File "C:\Program Files\Python311\Lib\asyncio\streams.py", line 344, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\proactor_events.py", line 109, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 761, in call_soon
    self._check_closed()
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by vvuk** [comment]
Odd, it might be that the printer itself force closes the network connection and it did so before the host/sending side did. I'll add something to suppress exceptions if the data was transmitted properly.
